global using System.Linq;
global using System.Text;
global using System.Collections;
global using System.Collections.Generic;
global using HtmlAgilityPack;
global using System;
global using SunamoWikipedia._sunamo.SunamoArgs;
global using SunamoWikipedia._sunamo.SunamoHtml;
global using SunamoWikipedia._public.SunamoHtml.Html;
global using SunamoWikipedia._sunamo.SunamoExceptions;
global using System.Diagnostics;
global using System.Text.RegularExpressions;
global using System.Xml;
global using System.Reflection;
global using System.Net;
global using System.Diagnostics.CodeAnalysis;
global using SunamoWikipedia;
global using SunamoWikipedia._sunamo;
global using SunamoWikipedia._sunamo.SunamoCollectionsChangeContent;
global using SunamoWikipedia._sunamo.SunamoDictionary;
global using SunamoWikipedia._sunamo.SunamoRegex;
global using SunamoWikipedia._sunamo.SunamoString;
global using SunamoWikipedia._sunamo.SunamoStringSplit;
global using SunamoWikipedia._sunamo.SunamoData.Data;
global using SunamoWikipedia._sunamo.SunamoInterfaces.Interfaces;
global using SunamoWikipedia._sunamo.SunamoValues.Constants;
global using SunamoWikipedia._sunamo.SunamoValues.Values;

global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using Microsoft.Extensions.Logging;
global using NullLogger = Microsoft.Extensions.Logging.Abstractions.NullLogger;
