name: Build SunamoWikipedia

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoWikipedia
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoWikipedia/SunamoWikipedia.csproj

    - name: Build
      run: dotnet build SunamoWikipedia/SunamoWikipedia.csproj --configuration Release --no-restore

  test:
    name: Test SunamoWikipedia.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoWikipedia.Tests/SunamoWikipedia.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoWikipedia.Tests/SunamoWikipedia.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoWikipedia.Tests/SunamoWikipedia.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
